stages:
  - test
  - upload

include:
  - template: Security/SAST.gitlab-ci.yml

defectdojo_upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST "${DD_URL}/api/v2/import-scan/" \
      -H "Authorization: Token ${DD_API_TOKEN}" \
      -F "active=true" \
      -F "verified=true" \
      -F "scan_type=GitLab SAST Report" \
      -F "engagement=1" \
      -F "file=@gl-sast-report.json"
  dependencies:
    - semgrep-sast
  when: always
